<?xml version="1.0" encoding="UTF-8" ?>
<definitions name="test"
    targetNamespace="http://localhost/soap"
    xmlns:tns="http://localhost/soap"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <!-- Definizione della richiesta -->
    <message name="salutinoRequest">
        <part name="name" type="xsd:string"/>
    </message>

    <!-- Definizione della risposta -->
    <message name="salutinoResponse">
        <part name="return" type="xsd:string"/>
    </message>

    <!-- Porta -->
    <portType name="SalutinoPortType">
        <operation name="salutino">
            <input message="tns:salutinoRequest" />
            <output message="tns:salutinoResponse" />
        </operation>
    </portType>

    <!-- Binding -->
    <binding name="SalutinoBinding" type="tns:SalutinoPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="salutino">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>

    <!-- Servizio -->
    <service name="SalutinoService">
        <port name="SalutinoPort" binding="tns:SalutinoBinding">
            <soap:address location="http://localhost/soap/server.php" />
        </port>
    </service>
</definitions>


