<?xml version="1.0"?>
<definitions name="test"
    targetNamespace="http://URL_CARTELLA_SERVER_SOAP"
    xmlns:tns="http://URL_CARTELLA_SERVER_SOAP"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <!-- il servizio riceve il nome, che è di tipo stringa -->
    <message name="salutinoRequest">
        <part name="name" type="xsd:string"/>
    </message>

    <!-- definizione del messaggio di risposta -->
    <message name="salutando">
        <part name="salutation" type="xsd:string"/>
    </message>

    <!-- definizione del portType cche descrive l'operazione disponibile -->
    <portType name="PortTType">
        <operation name="salutino">
            <input message="tns:salutinoRequest" />
            <output message="tns:salutando" />
        </operation>
    </portType>

    <!-- definizione del binding (specifica il protocollo SOAP) -->
    <binding name="Binding" type="tns:PortTType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="salutino">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>

    <!-- documentazione del servizio -->
    <documentation>Servizio SOAP per restituire un saluto personalizzato</documentation>

    <!-- definizione del servizio e della sua posizione -->
    <service name="SalutinoService">
        <port name="Portuccia" binding="tns:Binding">
            <soap:address location="http://URL_SCRIPT_PHP_SERVER_SOAP" />
        </port>
    </service>
</definitions>

